version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached     
      - ~/.ssh/id_ed25519:/home/vscode/.ssh/id_ed25519:cached
      - ~/.ssh/id_ed25519.pub:/home/vscode/.ssh/id_ed25519.pub:cached
    networks:
      - general
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - general      
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:

networks:
  general:  